name = "Stingray"
uuid = "2045e982-6adb-4e09-8364-0d2cc8a3fe4f"
authors = ["Aman Pandey"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
